-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Makes hyprsunset do nothing to the screen by default

-- Without this, the default applies some tint to the monitor

hl.config({
    profile = {
        time = "07:00",
        identity = true,
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output

-- To enable auto switch to nightlight, set in your .config/hypr/autostart:

-- exec-once = uwsm app -- hyprsunset

-- and use the following:

-- profile {

--     time = 20:00

--     temperature = 4000

-- }
