# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

source = ~/.config/hypr/monitors-default.conf

# Define a variable for the hostname
$HOSTNAME = $(hostname)

# Then use the variable in a conditional block
# hyprlang if HOSTNAME == "js-t480"
source = ~/.config/hypr/monitors-t480.conf
# hyprlang endif
