-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("GDK_SCALE", 1)

-- Big external monitor
hl.monitor({
  output   = "desc:Dell Inc.DELL S3225QS HG6SF94",
  mode     = "2560x1440@60",
  position = "0x0",
  scale    = 1,
})

-- Medium external monitor
hl.monitor({
  output    = "desc:ASUSTek COMPUTER INC ASUS VG24V 0x0002571B",
  mode      = "1920x1080@60",
  position  = "-1080x-480",
  scale     = 1,
  transform = 1,
})
