-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    screencopy = {
        allow_token_by_default = true,
        custom_picker_binary = "hyprland-preview-share-picker",
    },
})
-- NOTE: Section 'screencopy' may be a plugin or custom section; verify the output
