# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config file
bind r source-file ~/.tmux.conf

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'
set -g status-style 'fg=red'

# statusbar - list of open windows in the current session
set -g status-position bottom
set -g status-justify centre 

# Format of the left corner - hostname
set -g status-left '[#(hostname)] [tmux]'
set -g status-left-length 32

# Format for the right corner - datetime
set -g status-right-style 'fg=white bg=black'
set -g status-right '[%Y-%m-%d %I:%M%P]'
set -g status-right-length 32

# Format for the middle - active window
setw -g window-status-current-style 'fg=white bg=blue'
setw -g window-status-current-format '[#I #W #F]'

# Format for the middle - non active windows
setw -g window-status-style 'fg=white bg=black'
setw -g window-status-format ' #I #W #F '

